### ISSUE TITLE
imagenet_train.py--line 310

### ISSUE THREAD

**Issue by yangzhipeng1108** [AI-HPC-Research-Team/AIPerf#8]
context = zmq.Context()
socket = context.socket(zmq.REQ)
tmpstr = 'tcp://' + args.ip + ':800081'
socket.connect(tmpstr)
nni.get_next_parameter(socket)

What does this code do？

nni.get_next_parameter(socket)----------The code stops running at this line

**Comment by YueZhou-oh** [comment]
Hello, It's for communication between master and slave nodes.
Make sure master and slave ip is set right and connectable, moreover, you need to configure NFS and Slurm with reference to README.md
